### ISSUE TITLE
系统更新后会出现不能启动的情况

### ISSUE THREAD

**Issue by yizg20** [ventoy/vtoyboot#1]
是否可以增加更新系统后会自动运行vtoyboot来更新启动内核，或者修复这个更新内核后无法启动的问题，或者能否提供一个无法进入系统的修复启动项方案

**Comment by ventoy** [comment]
使用最新的1.0.4版本试试

**Comment by yizg20** [comment]
> 使用最新的1.0.4版本试试

**Comment by yizg20** [comment]
> > 使用最新的1.0.4版本试试

测试已经完美解决，牛！
![Screenshot_20201101_191901](https://user-images.githubusercontent.com/40365161/97801886-dc260880-1c7a-11eb-985e-364f0113e187.png)
![Screenshot_20201101_193948](https://user-images.githubusercontent.com/40365161/97801893-e2b48000-1c7a-11eb-98eb-26e7c53dfceb.png)
