### ISSUE TITLE
manjaro cinnamon Minimal 21.0.7 in .vdi.vtoy: can't boot in Legacy BIOS mode

### ISSUE THREAD

**Issue by candrapersada** [ventoy/vtoyboot#12]
why when using Manjaro in Legacy BIOS mode it doesn't boot?
```
device-mapper: reload ioctl on ventoy (254:0) failed: Invalid argument
Command falied.
```
![image](https://user-images.githubusercontent.com/36833664/124684441-5d642800-def9-11eb-8f58-6895714d7e28.png)
manjaro-cinnamon-21.0.7-minimal-210623-linux510.iso
[vtoyboot-1.0.14.tar.gz](https://github.com/ventoy/vtoyboot/files/6771331/vtoyboot-1.0.14.tar.gz)
vdiskchain-1.3

**Comment by ventoy** [comment]
How did you boot it ?  By Ventoy or by vdiskchain?
Can it boot ok when you copy it to USB and boot by Ventoy?
Can it boot ok when you copy it to the Hard disk and boot by Ventoy USB? (Boot vDisk at Local disk by Ventoy)[https://www.ventoy.net/en/plugin_vtoyboot.html]

**Comment by candrapersada** [comment]
> By Ventoy or by vdiskchain?

I use Ventoy boot to boot in UEFI mode and use vdiskchain to boot in Legacy BIOS from windows 10

> Can it boot ok when you copy it to the Hard disk and boot by Ventoy USB? 

OK

>  Can it boot ok in UEFI mode?

OK

**Comment by ventoy** [comment]
Can it boot ok if you use other bootloader with vdiskchain in Legacy BIOS mode ? (e.g.  grub4dos/grub2)

**Comment by candrapersada** [comment]
> Can it boot ok if you use other bootloader with vdiskchain in Legacy BIOS mode ?
ok

**Comment by ventoy** [comment]
So it maybe a compatibility problem with Grub2Win.
I only tested grub4dos and grub2.

**Comment by ventoy** [comment]
I don't have enough time to test for all type of bootloaders and I'm not familar with Grub2Win.

**Comment by candrapersada** [comment]
but still can't boot Manjaro in ventoy USB in Legacy BIOS mode
![gambar](https://user-images.githubusercontent.com/36833664/124853371-f8c7cc80-dfcf-11eb-88b5-43440d740d5d.png)

**Comment by ventoy** [comment]
Can it boot ok when you copy it to USB and boot by Ventoy in Legacy BIOS mode?

**Comment by ventoy** [comment]
Only manjaro has this problem? Did you test other distros(e.g. CentOS/Arch/Ubuntu)

**Comment by candrapersada** [comment]
> Can it boot ok when you copy it to USB and boot by Ventoy in Legacy BIOS mode?

ok

> Only manjaro has this problem?

yes

> Did you test other distros(e.g. CentOS/Arch/Ubuntu)

yes for Ubuntu

**Comment by ventoy** [comment]
In this problem:
1. You put the vtoy file in USB or harddisk?
2. May the file corrupted during copy?

**Comment by candrapersada** [comment]
> 1. You put the vtoy file in USB or harddisk?

harddisk

> 2. May the file corrupted during copy?

not

**Comment by ventoy** [comment]
If this vtoy file in harddisk, both legacy BIOS mode and UEFI mode can't boot. No matter whether you use Ventoy to boot it or use vdiskchain to boot it.

If this vtoy file in USB, both legacy BIOS mode and UEFI mode can boot ok with Ventoy.

Right?

**Comment by candrapersada** [comment]
not. only UEFI mode can boot Manjaro on ventoy. and legacy BIOS mode that won't boot into Manjaro

**Comment by candrapersada** [comment]
I have tested Manjaro on my harddisk but only UEFI works fine on Ventoy.

**Comment by ventoy** [comment]
Can you compress and share me the manjaro.vtoy file for test?

**Comment by candrapersada** [comment]
not always big

**Comment by candrapersada** [comment]
https://download.manjaro.org/cinnamon/21.0.7/manjaro-cinnamon-21.0.7-minimal-210623-linux510.iso

**Comment by ventoy** [comment]
I want your **vtoy** file for test, not the ISO file.

**Comment by ventoy** [comment]
What about the latest vtoyboot-1.0.15 ?

**Comment by candrapersada** [comment]
yes it works fine to boot in legacy BIOS mode.
but why should there be `.tar.gz `in the iso if you can go directly to vtoyboot without having to use the `.tar.gz `extract tool?

**Comment by ventoy** [comment]
good news.
iso is a read only file system.
In the script, some process(e.g. chmod, create temp file or log) need the write permission.
I provide iso file only for convenience to transfer the tar.gz file to the VM.

Since the problem has been fixed, I will close the issue now.
