### ISSUE TITLE
system bootorder not found

### ISSUE THREAD

**Issue by gland2015** [ventoy/vtoyboot#19]
system bootorder not found，启动centos时发生该问题

**Comment by ventoy** [comment]
影响功能吗？ 截个图看看？

**Comment by gland2015** [comment]
![5%~4DSFD@0I )SE24I_2JDC](https://user-images.githubusercontent.com/38042039/128181276-989759b8-9d45-42cd-9f45-68ab0dc34240.png)

**Comment by gland2015** [comment]
选择centos开机，就闪一下这段文字就重启了

**Comment by ventoy** [comment]
每次启动都是这样吗？

**Comment by gland2015** [comment]
是的

**Comment by gland2015** [comment]
对了，安装vtoyboot脚本时还有警告信息：grub module directory not find，is missing ?
但是最后还是安装成功了

**Comment by ventoy** [comment]
再用VirtualBox启动起来，执行一遍 vtoyboot.sh 截图看看。

**Comment by gland2015** [comment]
![image](https://user-images.githubusercontent.com/38042039/128183304-e18505fe-a0ad-42b7-9474-0427f715f73b.png)

**Comment by gland2015** [comment]
大佬这么看

**Comment by ventoy** [comment]
没看出问题。

你物理机上面有没有开启安全启动？ 开启的话关闭再试试。

**Comment by gland2015** [comment]
都关了的，我怀疑华硕主板有什么特性

**Comment by ventoy** [comment]
1. 确保安全启动确实关闭了。
2. 你先使用VirtualBox启动到系统里面，然后把  /boot/EFI/Boot/bootx64.efi 这个文件改个别的名字，然后把 
把 /boot/EFI/centos/grubx64.efi  拷贝为 /boot/EFI/Boot/bootx64.efi

命令如下：
```
mv  /boot/EFI/Boot/bootx64.efi  /boot/EFI/Boot/bootx64_backup.efi
cp /boot/EFI/centos/grubx64.efi /boot/EFI/Boot/bootx64.efi
```

然后退出系统之后，再使用Ventoy启动试试。

**Comment by ventoy** [comment]
另外，确认机器有没有关闭安全启动很简单。 如果你安装Ventoy的时候没有勾选 `安全启动支持` 这个选项，那么如果机器开启了安全启动，Ventoy是启动不了的。
如果你已经勾选了 `安全启动支持` 这个选项，你可以使用Ventoy安装工具做一次升级动作，（同版本也可以升级），在升级之前取消勾选 `安全启动支持` 这个选项，这样升级之后就是不支持安全启动的，这个时候如果Ventoy还能启动，则说明物理机器一定已经关闭了安全启动的。

**Comment by gland2015** [comment]
![LVHIZYS8V$8BU{5))$H`VWQ](https://user-images.githubusercontent.com/38042039/128587083-dae27691-e467-485b-aed9-874fd7783150.png)
只有/efi/EFI，多了个小写的efi。这样能启动成功，大佬还是强啊。
最后貌似是centos的显卡驱动问题，不过能正常使用。
![image](https://user-images.githubusercontent.com/38042039/128587157-94a96e68-67ac-496c-9dae-a7ce560fdd4e.png)

**Comment by gland2015** [comment]
之前的centos8再用虚拟机启动出了点问题：
![image](https://user-images.githubusercontent.com/38042039/128587192-688b1d5f-def0-495d-8a2b-eb38513f94e1.png)

**Comment by ventoy** [comment]
可能用VirtualBox启动又需要改回去吧。 你试试CentOS 7/Ubuntu之类的有问题吗？ 看看是主板问题还是系统相关？

**Comment by gland2015** [comment]
没看出来，之前centos8启动失败又用虚拟机启动过几次，不知道这次怎么就不行了，这次用的centos7。还有我都是用vmware workstation挂载物理磁盘的方式启动。

**Comment by gland2015** [comment]
centos这个启动问题有没有计划在脚本中修复，脚本mv 和 cp

**Comment by gland2015** [comment]
大佬对niumao这个vhd启动方案怎么看，[http://bbs.wuyou.net/forum.php?mod=viewthread&tid=336079&extra=page%3D1](http://bbs.wuyou.net/forum.php?mod=viewthread&tid=336079&extra=page%3D1)

**Comment by ventoy** [comment]
你也说了，这个问题不是每个机器上都有的，还不知道具体到底什么原因，暂时还没有修复计划。

niumao的VHD启动方案按我初步的理解，有个最大的问题。
以vhd文件放在NTFS格式的U盘中启动为例。在启动过程中是先通过ntfs-3g mount这个NTFS的分区，然后再从这个分区下找到对应的 vhd 文件进行二次mount处理。
这里面通过  ntfs-3g mount NTFS分区是走的 fuse，即用户态文件系统的形式，这个会对性能造成巨大的影响。即使是把U盘格式化成Linux原生支持的 ext/xfs 等文件系统，这里也实际上是叠加了2层文件系统，还是有性能损耗。
而Ventoy是通过device-mapper 直接按照vhd文件在U盘中的位置创建dm设备，几乎没有性能损失。
还有其他一些小问题，比如操作太复杂、支持类型不多等。

**Comment by gland2015** [comment]
好👍

**Comment by trymeouteh** [comment]
Has anyone solve this yet?

**Comment by ventoy** [comment]
@trymeouteh 
Have you tried the latest vtoyboot-1.0.20?
