### ISSUE TITLE
Manjaro和Ubuntu最新均无法启动

### ISSUE THREAD

**Issue by JamesLewisLiu** [ventoy/vtoyboot#21]
manjaro-i3-21.0.7-210623-linux510.iso
运行完脚本后通过Ventoy启动直接进Emergency

ubuntu-20.04.2.0-desktop-amd64.iso
ubuntu-20.04.0-server-amd64.iso
运行完脚本后通过Ventoy启动之后瞬间重启

均为刚创建完的VHD和VDI，大小100G，放在移动硬盘上单独的NTFS分区中（使用在磁盘最后保留一段空间选项）

**Comment by ventoy** [comment]
```
manjaro-i3-21.0.7-210623-linux510.iso
运行完脚本后通过Ventoy启动直接进Emergency
```

这个进入 Emergency 之后执行个命令：
```
vtoydump -v
```

**Comment by JamesLewisLiu** [comment]
>```
>manjaro-i3-21.0.7-210623-linux510.iso
>运行完脚本后通过Ventoy启动直接进Emergency
>```
>这个进入 Emergency 之后执行 2 个命令，然后把结果贴一下看看：
>```
>blkid
>vtoydump -v
>```
Manjaro用最新的vtoyboot之后又没问题了

>Ubuntu 启动瞬间重启有什么打印吗？
但是Ubuntu还是不行，任何输出都没有就直接重启了

**Comment by ventoy** [comment]
不知道和这个是不是类似原因：
https://github.com/ventoy/vtoyboot/issues/19

**Comment by JamesLewisLiu** [comment]
很奇怪，1.0.17怎么做都不行

1.0.17的Ubuntu的vdi用1.0.18升级之后也还是不行，但是重新做了一个之后又可以了。。。
