### ISSUE TITLE
UEFI无法启动

### ISSUE THREAD

**Issue by fake-programmer** [ventoy/vtoyboot#27]
根据教程制作的vdi，笔记本(神州战神、ThinkPad)设置为UEFI模式无法启动(屏幕显示 Reset System，然后自动重启)，
设置为Legacy可以。路径 /boot/efi 下为空。
系统为 elementary OS 6 Odin (基于Ubuntu 20.04 LTS)。之前也尝试过 xubuntu-20.04.3-desktop-amd64.iso, 也是相同问题

**Comment by zym3122** [comment]
加1，我也是啊老哥

**Comment by ventoy** [comment]
参考下 https://github.com/ventoy/vtoyboot/issues/19

**Comment by ventoy** [comment]
请使用最新版本测试
