### ISSUE TITLE
vhd ubuntu-20.04.3 无法启动

### ISSUE THREAD

**Issue by fake-programmer** [ventoy/vtoyboot#31]
使用vbox并设置efi模式安装了ubuntu-20.04.3，执行了 sudo sh vtoyboot.sh 并成功。vhd在本地磁盘上。
第一次启动报错：缺少ventoy_vhdboot.img。(在此有个疑问ventoy_vhdboot.img不是用于启动Windows的么)
放入 ventoy_vhdboot.img，第二次启动也报错。见图。
![Snipaste_2021-12-16_11-25-10](https://user-images.githubusercontent.com/63443553/146312228-f8b2242d-d354-4972-9999-b29cef494185.png)
![IMG_20211216_112746-tuya](https://user-images.githubusercontent.com/63443553/146312251-a3cbe813-c25c-4d12-8151-56318348b8a9.jpg)
![IMG_20211216_125046-tuya](https://user-images.githubusercontent.com/63443553/146312264-bca84076-306a-4e25-9775-7c546a1129fa.jpg)

**Comment by a1ive** [comment]
改扩展名为vtoy。
https://www.ventoy.net/cn/plugin_vtoyboot.html

**Comment by fake-programmer** [comment]
改成了.vtoy的，因为U盘空间不够，通过ventoy_grub.cfg的方式启动的，然后就是如上的错误

**Comment by fake-programmer** [comment]
问题已解决。
https://github.com/ventoy/Ventoy/issues/1377
