### ISSUE TITLE
如何实现ventoy&FydeOS to go？

### ISSUE THREAD

**Issue by IceAge0** [ventoy/vtoyboot#33]
我希望在一个U盘上同时使用FydeOS和ventoy，目前我采取的方法是安装ventoy1.0.64时在磁盘最后保留一段空间，并使用FydeOS的安装工具的多系统安装进行。FydeOS似乎无法正确引导。请问如何解决这个问题？

**Comment by a1ive** [comment]
https://www.ventoy.net/cn/doc_chrome_os.html
