### ISSUE TITLE
centos7 无法启动

### ISSUE THREAD

**Issue by denwork** [ventoy/vtoyboot#35]
安装有个报错，提示找不到require_binaries命令。
![image](https://user-images.githubusercontent.com/21987200/154450354-bacfdae2-85c2-4091-b726-5198a266f527.png)

复制到u盘以后启动，可以到启动菜单界面，选择内核启动后。提示找不到linuxefi和initrdefi命令。

**Comment by ventoy** [comment]
新版本已经修复。
