### ISSUE TITLE
Unable to boot on Kali 2022.1 

### ISSUE THREAD

**Issue by richardzone** [ventoy/vtoyboot#44]
根据 https://www.ventoy.net/cn/plugin_vtoyboot.html 安装好系统并运行了 vtoyboot.sh ，关机使用 Ventoy 启动，进入如下界面：

**Comment by ventoy** [comment]
Legacy BIOS 模式还是UEFI模式？
执行 vtoyboot.sh 时有没有错误？ 最好再使用虚拟机启动，重新执行一次vtoyboot把 Log 发出来看一下。

**Comment by ventoy** [comment]
另外，在图中这个界面上执行     `cat   /tmp/vtoy.log`

**Comment by richardzone** [comment]
> Legacy BIOS 模式还是UEFI模式？ 执行 vtoyboot.sh 时有没有错误？ 最好再使用虚拟机启动，重新执行一次vtoyboot把 Log 发出来看一下。

1. UEFI 模式，设备是一台 Macbook Pro 16,1（只允许 GPT + EFI 启动）
2. 没有错误，因为没装 grub-i386 所以显示了 Warning 只允许 EFI 启动

**Comment by richardzone** [comment]
另外，使用最新的 Kali Weekly Build ISO （W14），也是一样的问题

**Comment by ventoy** [comment]
Ventoy 并不支持mac机器，所以能不能启动看人品的。

**Comment by richardzone** [comment]
原来是这样，其他 Live ISO 启动都是正常的
