### ISSUE TITLE
不支持多内核启动吗?

### ISSUE THREAD

**Issue by a1768623020** [ventoy/vtoyboot#7]
Centos7标准分区,只能启动第一个默认的内核,我有两个内核,一个是3.10的内核一个是5.4的内核,制作镜像时使用5.4内核启动的,拷贝到U盘上只能启动5.4的,3.10的找不到块设备.

**Comment by ventoy** [comment]
请使用最新的 vtoyboot-1.0.15 版本测试一下。

**Comment by a1768623020** [comment]
经测试可用,谢谢.
