### ISSUE TITLE
在archlinux 运行后报错binary not found : pdata tools

### ISSUE THREAD

**Issue by jycyouyas** [ventoy/vtoyboot#90]
![Screenshot from 2024-09-02 01-00-02](https://github.com/user-attachments/assets/969baef6-5323-4f2f-9f75-c608eb566d20)
具体如上图所示，搜索pdata tools后，也没得出什么头绪，可以告知具体要安装什么包，将这个问题解决吗？使用的版本是vtoyboot-1.0.35

**Comment by AyariaPrescott** [comment]
安装which和lvm2这两个包可以解决这个报错

**Comment by jycyouyas** [comment]
> 安装which和lvm2这两个包可以解决这个报错

我测试了一下，确实可以！非常感谢！

**Comment by jycyouyas** [comment]
> 安装which和lvm2这两个包可以解决这个报错

关闭

**Comment by kenis1108** [comment]
感谢感谢
